# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('open_id', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('link_man', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('date_update', models.DateField()),
                ('is_default', models.BooleanField()),
                ('province', models.CharField(max_length=255)),
                ('province_id', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('city_id', models.IntegerField()),
                ('area', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_domain', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('mall_name', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=255)),
                ('webchat_pay_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_domain', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('display_pic', models.CharField(max_length=255)),
                ('link_url', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_domain', models.CharField(help_text='\u5b50\u57df\u540d', max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('c_type', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('characteristic', models.CharField(max_length=255)),
                ('display_pic', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('number_order', models.IntegerField()),
                ('original_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('number_good_reputation', models.IntegerField(default=0)),
                ('weight', models.FloatField()),
                ('stores', models.IntegerField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AppConfig')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=255)),
                ('number_goods', models.IntegerField()),
                ('goods_price', models.FloatField()),
                ('logistics_price', models.FloatField()),
                ('total', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('tracking_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('goods', models.ManyToManyField(to='app.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('openid', models.CharField(max_length=255)),
                ('result_code', models.CharField(max_length=255)),
                ('err_code', models.CharField(max_length=255)),
                ('err_code_des', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=255)),
                ('bank_type', models.CharField(max_length=255)),
                ('fee_type', models.CharField(max_length=255)),
                ('total_fee', models.IntegerField()),
                ('settlement_total_fee', models.IntegerField()),
                ('cash_fee', models.IntegerField()),
                ('cash_fee_type', models.CharField(max_length=255)),
                ('coupon_fee', models.IntegerField()),
                ('coupon_count', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='app.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pic', models.ImageField(upload_to='img')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='app.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='WechatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('open_id', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('register_type', models.CharField(max_length=255)),
                ('register_ip', models.CharField(max_length=255)),
                ('last_login', models.DateField()),
                ('phone', models.CharField(max_length=255)),
                ('union_id', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('status', models.CharField(default='default', max_length=255)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AppConfig')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WechatUser'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Goods'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addr', to='app.WechatUser'),
        ),
    ]
