# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171024_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='pic',
        ),
        migrations.AddField(
            model_name='picture',
            name='goods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Goods'),
            preserve_default=False,
        ),
    ]
