# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171024_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='host',
            field=models.CharField(default='http://wechatmall.bestaliceroom.xyz', max_length=255),
            preserve_default=False,
        ),
    ]
