# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appconfig_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='app.Goods'),
        ),
    ]
