# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_payment_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('man', models.IntegerField()),
                ('jian', models.IntegerField()),
                ('status', models.IntegerField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AppConfig')),
            ],
        ),
    ]
