# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='code',
            field=models.CharField(default='', max_length=255, verbose_name='\u5907\u6ce8'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='link_man',
            field=models.CharField(max_length=255, verbose_name='\u8054\u7cfb\u4eba'),
        ),
    ]
