# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171106_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='\u6807\u9898')),
                ('cover', models.ImageField(upload_to='img', verbose_name='\u5c01\u9762\u56fe\u7247')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('date', models.DateTimeField(verbose_name='\u65e5\u671f')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AppConfig')),
            ],
        ),
    ]
